trigger: none

pr:
- master

pool: GCA-AgentPool

variables:
# Links to the variable group containing your GEMINI_API_KEY and DOCKER_HUB_USER.
- group: 'Gemini-DevSecOps-Keys' 
# We will define more specific image names directly in the build tasks.

stages:
- stage: Scan_And_Analyze
  displayName: 'Run Scans & AI Analysis'
  jobs:
  - job: DevSecOps_Scan
    displayName: 'Run Security and Code Scans'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.52.2/trivy_0.52.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.52.2_Linux-64bit.deb
        wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
        tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
        sudo mv gitleaks /usr/local/bin/
        python3 -m venv bandit-env
        source bandit-env/bin/activate
        pip install bandit
      displayName: 'Install Scanning Tools (Trivy, Gitleaks, Bandit)'

    - script: |
        echo "Running Gitleaks for secret detection..."
        gitleaks detect --source . -r gitleaks_report.json || true
        
        echo "Running Bandit for Python SAST..."
        # Activate the virtual environment to ensure the bandit command is found
        source bandit-env/bin/activate
        bandit -r . -f json -o bandit_report.json || true
      displayName: 'Run SAST and Secret Scans'
      
    # FIX: Replaced the single Docker build task with two separate tasks,
    # one for each Dockerfile.
    - task: Docker@2
      displayName: 'Build Static Site Docker Image'
      inputs:
        command: 'build'
        # Correctly points to the first Dockerfile
        dockerfile: 'static-site/Dockerfile'
        # Assigns a unique and descriptive name to the image
        repository: '$(DOCKER_HUB_USER)/gemini-demo-static-site' 
        tags: '$(Build.BuildId)'

    - task: Docker@2
      displayName: 'Build Flask App Docker Image'
      inputs:
        command: 'build'
        # Correctly points to the second Dockerfile
        dockerfile: 'flask-app/Dockerfile' 
        # Assigns a unique and descriptive name to the image
        repository: '$(DOCKER_HUB_USER)/gemini-demo-flask-app'
        tags: '$(Build.BuildId)'

    # FIX: Updated the scanning step to analyze both images built in the previous tasks.
    - script: |
        echo "Scanning Docker images with Trivy for vulnerabilities..."
        trivy image --format json --output trivy_static_site_report.json --severity HIGH,CRITICAL $(DOCKER_HUB_USER)/gemini-demo-static-site:$(Build.BuildId) || true
        trivy image --format json --output trivy_flask_app_report.json --severity HIGH,CRITICAL $(DOCKER_HUB_USER)/gemini-demo-flask-app:$(Build.BuildId) || true
        
        echo "Generating SBOM for Docker images with Trivy..."
        trivy image --format cyclonedx --output sbom_static_site.xml $(DOCKER_HUB_USER)/gemini-demo-static-site:$(Build.BuildId)
        trivy image --format cyclonedx --output sbom_flask_app.xml $(DOCKER_HUB_USER)/gemini-demo-flask-app:$(Build.BuildId)
      displayName: 'Run Trivy Image Scans & Generate SBOMs'

    - script: |
        echo "Installing Gemini CLI..."
        npm install -g @google/gemini-cli@0.1.18
      displayName: 'Install Gemini CLI v0.1.18'

    # FIX: Updated the prompt to reference the new, separate container reports and SBOMs.
    - script: |
        export GEMINI_API_KEY=$(GEMINI_API_KEY)
        
        PROMPT="""
        You are an expert DevSecOps review agent. A pull request has been submitted.
        Your task is to perform a comprehensive review based on the provided code and scan reports.

        **Scan Reports:**
        - SAST Report: @bandit_report.json
        - Secret Scan Report: @gitleaks_report.json
        - Container Vulnerability Report (Static Site): @trivy_static_site_report.json
        - Software Bill of Materials (Static Site): @sbom_static_site.xml
        - Container Vulnerability Report (Flask App): @trivy_flask_app_report.json
        - Software Bill of Materials (Flask App): @sbom_flask_app.xml

        **Instructions:**
        1. **Code Review:** Review the code changes in this pull request. Provide specific, actionable suggestions for improvements.
        2. **Security Analysis:** Analyze all provided security reports for both services.
        3. **Policy Check:** Based on the rules in @GEMINI.md, determine if this PR passes or fails. State the result clearly (e.g., "POLICY CHECK: PASS" or "POLICY CHECK: FAIL"). If it fails, list the exact reasons.
        4. **Generate Summary:** Combine all findings into a single, well-formatted markdown report suitable for a pull request comment. Start with the policy check result.
        """
        
        gemini -p "$PROMPT" --context GEMINI.md > gemini_review.md
      displayName: 'Run Gemini CLI for AI Analysis'
      
    - task: PowerShell@2
      displayName: 'Post Gemini Review to PR'
      inputs:
        targetType: 'inline'
        script: |
          $reviewContent = Get-Content -Raw -Path gemini_review.md | ConvertTo-Json
          $url = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=6.0"
          $headers = @{
              "Authorization" = "Bearer $(System.AccessToken)"
              "Content-Type" = "application/json"
          }
          $payload = @"
          {
            "comments": [
              {
                "parentCommentId": 0,
                "content": $reviewContent,
                "commentType": 1
              }
            ],
            "status": 1
          }
          "@
          Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $payload
      condition: succeeded()