trigger: none

pr:
- master

pool: GCA-AgentPool

variables:
- group: 'Gemini-DevSecOps-Keys'

stages:
- stage: Scan_And_Analyze
  displayName: 'Run Scans & AI Analysis'
  jobs:
  - job: DevSecOps_Scan
    displayName: 'Run Security and Code Scans'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.52.2/trivy_0.52.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.52.2_Linux-64bit.deb
        wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
        tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
        sudo mv gitleaks /usr/local/bin/
        python3 -m venv bandit-env
        source bandit-env/bin/activate
        pip install bandit
      displayName: 'Install Scanning Tools (Trivy, Gitleaks, Bandit)'

    - script: |
        echo "Running Gitleaks..."
        gitleaks detect --source . -r gitleaks_report.json || true
        
        echo "Running Bandit..."
        source bandit-env/bin/activate
        bandit -r . -f json -o bandit_report.json || true
      displayName: 'Run SAST and Secret Scans'
      
    - task: Docker@2
      displayName: 'Build Static Site Docker Image'
      inputs:
        command: 'build'
        dockerfile: 'static-site/Dockerfile'
        repository: '$(DOCKER_HUB_USER)/gemini-demo-static-site' 
        tags: '$(Build.BuildId)'

    - task: Docker@2
      displayName: 'Build Flask App Docker Image'
      inputs:
        command: 'build'
        dockerfile: 'flask-app/Dockerfile' 
        repository: '$(DOCKER_HUB_USER)/gemini-demo-flask-app'
        tags: '$(Build.BuildId)'

    - script: |
        echo "Scanning Docker images..."
        trivy image --format json --output trivy_static_site_report.json --severity HIGH,CRITICAL $(DOCKER_HUB_USER)/gemini-demo-static-site:$(Build.BuildId) || true
        trivy image --format json --output trivy_flask_app_report.json --severity HIGH,CRITICAL $(DOCKER_HUB_USER)/gemini-demo-flask-app:$(Build.BuildId) || true
        
        echo "Generating SBOMs..."
        trivy image --format cyclonedx --output sbom_static_site.xml $(DOCKER_HUB_USER)/gemini-demo-static-site:$(Build.BuildId)
        trivy image --format cyclonedx --output sbom_flask_app.xml $(DOCKER_HUB_USER)/gemini-demo-flask-app:$(Build.BuildId)
      displayName: 'Run Trivy Image Scans & Generate SBOMs'

    - script: |
        echo "Installing Gemini CLI..."
        npm install -g @google/gemini-cli@0.1.18
      displayName: 'Install Gemini CLI v0.1.18'

    # FIX: The entire gemini command block has been rewritten to use a heredoc.
    # This prevents the shell from misinterpreting the prompt's content.
    - script: |
        export GEMINI_API_KEY=$(GEMINI_API_KEY)

        # Use a heredoc (<<PROMPT) to pass the multi-line string directly to gemini stdin
        gemini > gemini_review.md <<PROMPT
        You are an expert DevSecOps review agent. A pull request has been submitted.
        Your task is to perform a comprehensive review based on the provided code and scan reports.

        **Primary Instructions & Policies:**
        - Your core rules for this review are in the context file: @GEMINI.md

        **Scan Reports to Analyze:**
        - SAST Report: @bandit_report.json


        **Your Tasks:**
        2.  **Security Analysis:** Scrutinize all security reports against the policies in @GEMINI.md.
        4.  **Generate Summary:** Create a final, well-formatted markdown report for the PR comment, starting with the policy check result.
        PROMPT
      displayName: 'Run Gemini CLI for AI Analysis'
      
    - task: PowerShell@2
      displayName: 'Post Gemini Review to PR'
      inputs:
        targetType: 'inline'
        script: |
          $reviewContent = Get-Content -Raw -Path gemini_review.md | ConvertTo-Json
          $url = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=6.0"
          $headers = @{
              "Authorization" = "Bearer $(System.AccessToken)"
              "Content-Type" = "application/json"
          }
          $payload = @"
          {
            "comments": [
              {
                "parentCommentId": 0,
                "content": $reviewContent,
                "commentType": 1
              }
            ],
            "status": 1
          }
          "@
          Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $payload
      condition: succeeded()
